In [82]:
import tensorflow as tf

**Scalars and vectors**

In [ ]:
#scalar
tensor_zero_dimention=tf.constant(4)
print(tensor_zero_dimention)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
#one dim
tensor_one_dim=tf.constant([2,0,-3])
print(tensor_one_dim)

tf.Tensor([ 2  0 -3], shape=(3,), dtype=int32)


In [ ]:
tensor_two_d=tf.constant([[1,2,0],[3,4,3],[9,90,0]])
print(tensor_two_d)

tf.Tensor(
[[ 1  2  0]
 [ 3  4  3]
 [ 9 90  0]], shape=(3, 3), dtype=int32)


In [ ]:
print(tensor_two_d.shape)

(3, 3)


In [ ]:
print(tensor_two_d.ndim)

2


In [ ]:
#setting data type
tens_dtype=tf.constant([2,0,-3,8],dtype=tf.float32)
print(tens_dtype)

#dtype here is not int but float

tf.Tensor([ 2.  0. -3.  8.], shape=(4,), dtype=float32)


**Data types and casting**

https://www.tensorflow.org/api_docs/python/tf/dtypes

In [ ]:
tens_dtype=tf.cast(tens_dtype,dtype=tf.int16)
print(tens_dtype)

tf.Tensor([ 2  0 -3  8], shape=(4,), dtype=int16)


**Multi dimentional arrays**

In [ ]:
import numpy as np

In [ ]:
np_array=np.array([1,2,4])
print(np_array)

[1 2 4]


In [ ]:
conv_to_tensor=tf.convert_to_tensor(np_array)

In [ ]:
conv_to_tensor

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 4])>

In [ ]:
eye_tens=tf.eye(num_rows=5,
                num_columns=3,
                batch_shape=None,
                dtype=tf.dtypes.float32,
                name=None
                )
print(eye_tens)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(5, 3), dtype=float32)


In [ ]:
fill_tensor=tf.fill([3,4],5,name=None)
print(fill_tensor)

tf.Tensor(
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]], shape=(3, 4), dtype=int32)


In [ ]:
ones=tf.ones([5,5],dtype=tf.dtypes.float32,name=None)
print(ones)

tf.Tensor(
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]], shape=(5, 5), dtype=float32)


In [ ]:
#ones like

sample=tf.constant([[1,2,3],[4,6,7]])
one_like_tensor=tf.ones_like(sample)
print(one_like_tensor)

tf.Tensor(
[[1 1 1]
 [1 1 1]], shape=(2, 3), dtype=int32)


In [ ]:
zeroz=tf.zeros([3,4],tf.int32)
print(zeroz)

tf.Tensor(
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)


In [ ]:
print(tf.shape(zeroz))

tf.Tensor([3 4], shape=(2,), dtype=int32)


**Random**

In [ ]:
"""
tf.random.normal(
    shape,
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
 """

'\ntf.random.normal(\n    shape,\n    mean=0.0,\n    stddev=1.0,\n    dtype=tf.dtypes.float32,\n    seed=None,\n    name=None\n)\n '

In [ ]:
tf.random.normal(
    [2,3],
    mean=0.0,
    stddev=1.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 0.892274  , -0.06854755, -0.45444527],
       [-1.026941  , -1.8718371 , -0.2567551 ]], dtype=float32)>

In [ ]:
tf.random.uniform([3,3],
                  minval=0,
                  maxval=1,
                  dtype=tf.dtypes.float32,
                  seed=None,
                  name=None)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.52294445, 0.81186056, 0.69279814],
       [0.05338955, 0.64232063, 0.09153891],
       [0.78649545, 0.48432827, 0.1665535 ]], dtype=float32)>

https://www.acsu.buffalo.edu/~adamcunn/probability/binomial.html <br>
choose binomial from the bar and change

In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
tf.random.set_seed(5)
print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

print(tf.random.uniform(shape=[3,],maxval=5,dtype=tf.int32,seed=10))

tf.Tensor([4 3 1], shape=(3,), dtype=int32)
tf.Tensor([4 3 2], shape=(3,), dtype=int32)
tf.Tensor([1 1 1], shape=(3,), dtype=int32)
tf.Tensor([1 3 3], shape=(3,), dtype=int32)


In [ ]:
#indexing
ten=tf.constant([3,2,5,6,74,2,2])
print(ten[0:4])

tf.Tensor([3 2 5 6], shape=(4,), dtype=int32)


In [ ]:
#range
print(tf.range(2,6))

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [ ]:
#abs
tf.math.abs(-12.3)

<tf.Tensor: shape=(), dtype=float32, numpy=12.3>

In [ ]:
tf.abs(12-4.3j)

<tf.Tensor: shape=(), dtype=float64, numpy=12.747156545677157>

In [85]:
import math
tf.sqrt((12*12)+(4.3*4.3))

<tf.Tensor: shape=(), dtype=float32, numpy=12.747157>

**Math operations**

1.   add
2.   mul .
3.    ....




In [65]:
x=tf.constant([[2,20,30,3,126],
                      [3,11,160,1,8],
                      [14,34,56,7,70]])
print(tf.math.argmax(x))

tf.Tensor([2 2 1 2 0], shape=(5,), dtype=int64)


In [66]:
print(tf.math.argmin(x))

tf.Tensor([0 1 0 1 1], shape=(5,), dtype=int64)


In [71]:
print(tf.math.argmax(x,axis=0))

tf.Tensor([2 2 1 2 0], shape=(5,), dtype=int64)


In [72]:
print(tf.math.argmin(x,1))

tf.Tensor([0 3 3], shape=(3,), dtype=int64)


In [73]:
print(tf.math.argmin(x,0))

tf.Tensor([0 1 0 1 1], shape=(5,), dtype=int64)


In [83]:
 #redice sum will find sum
 ten=tf.constant([[1,2,0],
  [3,5,-1],
   [1,5,6],
    [2,3,4]])
 print(tf.math.reduce_sum(ten,axis=None,keepdims=False,name=None))

tf.Tensor(31, shape=(), dtype=int32)


In [76]:
 print(tf.math.reduce_min(ten,axis=None,keepdims=False,name=None))

tf.Tensor(-1, shape=(), dtype=int32)


In [77]:
 print(tf.math.reduce_max(ten,axis=None,keepdims=False,name=None))

tf.Tensor(6, shape=(), dtype=int32)


In [78]:
print(tf.math.reduce_sum(ten,axis=0,keepdims=False,name=None))

tf.Tensor([ 7 15  9], shape=(3,), dtype=int32)


In [79]:
print(tf.math.reduce_sum(ten,axis=1,keepdims=False,name=None))

tf.Tensor([ 3  7 12  9], shape=(4,), dtype=int32)


In [87]:
tens=tf.constant([[1,2,-0],
 [3,5,100]
 ,[1,5,6],
  [2,3,8]],dtype=tf.float16)
print(tf.math.reduce_std(tens,axis=0,keepdims=True,name=None))

tf.Tensor([[ 0.829  1.299 41.38 ]], shape=(1, 3), dtype=float16)


In [88]:
tf.math.top_k(tens,k=1)

TopKV2(values=<tf.Tensor: shape=(4, 1), dtype=float16, numpy=
array([[  2.],
       [100.],
       [  6.],
       [  8.]], dtype=float16)>, indices=<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[1],
       [2],
       [2],
       [2]], dtype=int32)>)




1.   tf.linalg.matmul()
2.   @ used as operator for matmul
3.   tf.transpose
4.   x.T   #transpose
5.   tf.linalg.adjoint
6.   



In [89]:
#band part m,n indexes
#num_lower <0 || m-n <= num_lower || num_upper<0  || n-m <=num_upper
inp=tf.constant([[0,1,2,3],
                 [-1,0,1,2],
                 [-2,-1,0,1],
                 [-3,-2,-1,0]])
tf.linalg.band_part(inp,1,-1)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  2,  3],
       [-1,  0,  1,  2],
       [ 0, -1,  0,  1],
       [ 0,  0, -1,  0]], dtype=int32)>

In [90]:
tf.linalg.band_part(inp,2,1)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 0,  1,  0,  0],
       [-1,  0,  1,  0],
       [-2, -1,  0,  1],
       [ 0, -2, -1,  0]], dtype=int32)>



1.   tf.linalg.cross
2.   tf.linalg.det
3.   tf.linalg.inv
4.   tf.linalg.matrix_transpose
5.   tf.linalg.svd  #singular value decomposition





In [94]:
#einsum
a=np.array([[2,6,5,2],
            [2,-2,2,3],
            [1,5,4,0]])
b=np.array([[2,9,0,3,0],
            [3,6,8,-2,2],
            [1,3,5,0,1],
            [3,0,2,0,5]])
print(a.shape)
print(b.shape)
print("------")
print(np.matmul(a,b))
print("------")
print(np.einsum("ij,jk->ik",a,b))

(3, 4)
(4, 5)
------
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]
------
[[33 69 77 -6 27]
 [ 9 12  0 10 13]
 [21 51 60 -7 14]]


**expand dims**

In [97]:
ten_three_d=tf.constant([[[1,2,0],
                          [3,5,-1]],
                         [[10,2,0],
                          [1,0,2]],
                         [[5,8,0],
                          [2,7,0]],
                         [[2,1,9],
                          [4,-3,32]]
                         ])
print(ten_three_d)


tf.Tensor(
[[[ 1  2  0]
  [ 3  5 -1]]

 [[10  2  0]
  [ 1  0  2]]

 [[ 5  8  0]
  [ 2  7  0]]

 [[ 2  1  9]
  [ 4 -3 32]]], shape=(4, 2, 3), dtype=int32)


In [98]:
print(tf.expand_dims(ten_three_d,axis=0).shape)

(1, 4, 2, 3)


In [109]:
x=tf.constant([[2,3,4,5]])
print(x.shape)
print(tf.expand_dims(x,axis=0))

(1, 4)
tf.Tensor([[[2 3 4 5]]], shape=(1, 1, 4), dtype=int32)


**squeeze**

In [110]:
exp_x=tf.expand_dims(x,axis=0)
print(exp_x)

tf.Tensor([[[2 3 4 5]]], shape=(1, 1, 4), dtype=int32)


In [106]:
sq=tf.squeeze(exp_x,axis=None,name=None)
print(sq)

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [107]:
sq=tf.squeeze(exp_x,axis=0,name=None)
print(sq)

tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


**reshape**

In [112]:
print(x)

tf.Tensor([[2 3 4 5]], shape=(1, 4), dtype=int32)


In [113]:
print(tf.reshape(x,[4,]))

tf.Tensor([2 3 4 5], shape=(4,), dtype=int32)


In [115]:
## tf.concat

t1=[[1,2,3],[4,5,6]]
t2=[[7,8,9],[10,11,12]]

In [116]:
print(tf.constant(t1))

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [117]:
tf.concat([t1,t2],axis=0)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [118]:
tf.stack([t1,t2],axis=0)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [119]:
tf.stack([t1,t2],axis=1)

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]], dtype=int32)>

**padding**

In [120]:
t=tf.constant([[1,2,3],
               [4,5,6]])
paddings=tf.constant([[1,5],
                      [2,3]])
tf.pad(t,paddings,"CONSTANT",constant_values=0)
#one 0 above,five 0 below ,two 0 left,three 0 right

<tf.Tensor: shape=(8, 8), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 0, 0, 0],
       [0, 0, 4, 5, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>

 tf.gather is used to extract slices from a tensor based on specified indices. This can be particularly useful when you want to select specific elements or sub-tensors without reshaping or slicing the entire tensor.

 gather vs slicing
tf.gather: Allows you to gather specific indices across any axis of a tensor. You can gather non-contiguous elements or entire rows, columns, or slices based on index values.
Slicing: Primarily used for contiguous sub-tensors. You define a range of indices and extract elements in a straightforward way.

In [121]:

matrix = tf.constant([[10, 20, 30],
                      [40, 50, 60],
                      [70, 80, 90],
                      [100, 110, 120]], dtype=tf.float32)

indices = tf.constant([1, 3])  # We want to gather the 2nd and 4th rows

# Use tf.gather to get the specified rows
gathered_rows = tf.gather(matrix, indices)

print("Original Matrix:")
print(matrix.numpy())
print("\nGathered Rows:")
print(gathered_rows.numpy())


Original Matrix:
[[ 10.  20.  30.]
 [ 40.  50.  60.]
 [ 70.  80.  90.]
 [100. 110. 120.]]

Gathered Rows:
[[ 40.  50.  60.]
 [100. 110. 120.]]


**Ragged tensors**

TensorFlow is used to create ragged tensors, which are tensors with varying shapes or sizes along one or more axes. This is particularly useful for handling data that doesn't fit into a standard rectangular shape, such as lists of varying lengths

In [122]:
import tensorflow as tf

# Creating a ragged tensor from nested lists
ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6]])

print("Ragged Tensor:")
print(ragged_tensor)
print("\nShape:", ragged_tensor.shape)


Ragged Tensor:
<tf.RaggedTensor [[1, 2, 3], [4, 5], [6]]>

Shape: (3, None)


**ragged boolean mask**

In [123]:
import tensorflow as tf

# Create a ragged tensor
ragged_tensor = tf.ragged.constant([[1, 2, 3], [4, 5], [6, 7, 8]])

print("Original Ragged Tensor:")
print(ragged_tensor)

# Create a boolean mask
mask = tf.ragged.constant([[True, False, True], [False, True], [True, True, False]])

# Apply the boolean mask
filtered_tensor = tf.ragged.boolean_mask(ragged_tensor, mask)

print("\nFiltered Ragged Tensor:")
print(filtered_tensor)


Original Ragged Tensor:
<tf.RaggedTensor [[1, 2, 3], [4, 5], [6, 7, 8]]>

Filtered Ragged Tensor:
<tf.RaggedTensor [[1, 3], [5], [6, 7]]>


**sparse tensors**

In [124]:
tens=tf.sparse.SparseTensor(
    indices=[[1,1],[3,4]],values=[11,56],dense_shape=[5,6]
)


In [125]:
tens

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 56], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))

In [126]:
print(tf.sparse.to_dense(tens))

tf.Tensor(
[[ 0  0  0  0  0  0]
 [ 0 11  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0 56  0]
 [ 0  0  0  0  0  0]], shape=(5, 6), dtype=int32)


**strings**



1.   lower
2.   upper



**Variables**

In [127]:
x=tf.constant([1,2])
x_var=tf.Variable(x,name='var1')

In [128]:
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>


In [129]:
x_var.assign([2,3])

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [131]:
print(x_var)

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>


In [132]:
x_var.assign_sub([1,1])
x_var

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([1, 2], dtype=int32)>

In [133]:
x_var.assign_add([1,1])
x_var

<tf.Variable 'var1:0' shape=(2,) dtype=int32, numpy=array([2, 3], dtype=int32)>

In [136]:
with tf.device('GPU:0'):
  x_var=tf.Variable(0.3)
  print(x_var.device)
print(x_var.device)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0


In [137]:


import tensorflow as tf

# Check if a GPU is available
gpus = tf.config.list_physical_devices('GPU')

if gpus:
    # GPU is available
    print("GPU is available. Executing GPU code...")

    with tf.device('GPU:0'):
        # Place any GPU-specific code here
        x_var = tf.Variable(0.3)
        print(f"x_var is on {x_var.device}")

else:
    # No GPU available
    print("No GPU found. Executing CPU code...")

    with tf.device('CPU:0'):
        # Place any CPU-specific code here
        x_var = tf.Variable(0.3)
        print(f"x_var is on {x_var.device}")


No GPU found. Executing CPU code...
x_var is on /job:localhost/replica:0/task:0/device:CPU:0
